swagger: '2.0'
info:
  title: The API (from base)
  description: API description (from base)
  version: v1.0.0
# CHANGE LOG
# 07-05-2018: Initial version
# 10-31-2018: Made DOA Approver User Id optional on the input parameters
# 11-05-2018: Changed input parameter doaSubTypeCode to array type
host: thehost.com
# array of all schemes that your API supports
schemes:
- https
# will be prefixed to all paths
basePath: /base-path/v1
x-what-is-maximum-number-of-records-that-could-be-returned: 1
produces:
- application/json
- application/xml
paths: {}
definitions: {}